### PR TITLE
Week 4 work - saving to SQLite

### PR DESCRIPTION
**Pull request by AngeloStavrow**
Adds a **storageController.js** file that initializes and updates the database.

Test this by:

1. [Remixing the starter app](https://glitch.com/edit/#!/remix/rss-firehose-save2sqlite) and seeing if the database initializes correctly.
2. Passing a [url-encoded](https://www.urlencoder.org/) RSS feed URL to `your-remix.glitch.com/api/parse/:feed` and seeing if it is added to the database properly.
3. Pass the same feed a second time and make sure it doesn't get duplicated in the database.
4. Delete some newer records from the `entry` table of the database, then pass the feed in a third time and confirm that only those entries you deleted get re-added

### CODE REVIEW

**Review by melissamcewen — COMMENTED** [review]
Tested and worked for me. Except for #4 what's the best way to test that?

**Comment by melissamcewen** [comment]
Also really liked the console messages

**Comment by AngeloStavrow** [comment]
> Tested and worked for me. Except for #4 what's the best way to test that?

Oh, sorry about that oversight @melissamcewen! You can drop into the terminal and do the following:

```
# Launch SQLite's CLI
$ sqlite3

# Open the database file
sqlite> .open .data/sqlite.db

# Delete any records from the `entry` table newer than 27 April 2020 @ 3:06PM UTC
sqlite> DELETE FROM entry WHERE publishDate > 1588000000000;

# Quite the SQLite CLI
sqlite> .quit
```

**Comment by melissamcewen** [comment]
Great looks good!

**Pull request merged**
